### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by Miriamec29** [neurodevs/node-lsl#3]
Hello. I have some questions: is the package ready to install in a PC? If yes, how can i install the package in my pc? Are there some aditional dependencies that i have to install before node-lsl? Thank u!!

**Comment by eric-yates** [comment]
My apologies, I just saw this issue! This package was developed and tested on MacOS, so I can't guarantee that it'll run on a PC. You can test it to see if it works by doing this on a command line in a Node project:

`npm install @neurodevs/node-lsl`

That command will handle installing all dependencies for the package. I'll create documentation soon about usage and add it to the README!

**Comment by eric-yates** [comment]
My apologies, I just saw this issue. I've updated the documentation with installation and usage instructions. @Miriamec29, please let me know if you need any further help!
